name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - run: sdkmanager "build-tools;29.0.3" "platforms;android-10" "platforms;android-17"
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
    - name: dir
      run: ls build/outputs/apk
    - name: Allow Download of the app
      uses: actions/upload-artifact@v2
      with:
        name: dev-app
        path: build/outputs/apk
      
